export const projects = [
    {
        title: "Tetris",
        description: "Clásico juego de puzzle con bloques descendentes",
        image: "src/assets/background.svg",
        link: "#",
        clas: "md:w-[264px] md:h-[260px]",
        estado: "Completado",
        color: "bg-turquesa",
        items: [
            { iconClass: "fab fa-cuttlefish", name: "C++" },
            { iconClass: "fas fa-gamepad", name: "SFML" },
        ],
    },
    {
        title: "E-commerce",
        description: "Plataforma completa de ventas con sistema de pedidos",
        image: "src/assets/astro.svg",
        link: "#",
        clas: "md:w-[264px] md:h-[260px]",
        estado: "Completado",
        color: "bg-turquesa",
        items: [
            { iconClass: "fas fa-rocket", name: "Astro" },
            { iconClass: "fab fa-node-js", name: "Node.js" },
            { iconClass: "fas fa-database", name: "PostgreSQL" },
            { iconClass: "fab fa-js", name: "JavaScript" },
        ],
    },
    {
        title: "Blog Personal",
        description: "Espacio digital para compartir conocimientos y reflexiones",
        image: "src/assets/background.svg",
        link: "#",
        clas: "md:w-[555px] md:h-[250px]",
        estado: "Completado",
        color: "bg-turquesa",
        items: [
            { iconClass: "fas fa-rocket", name: "Astro" },
            { iconClass: "fab fa-js", name: "JavaScript" },
            { iconClass: "fas fa-palette", name: "Tailwind" },
        ],
    },
    {
        title: "Landing Page Jardineria",
        description: "Sitio promocional para servicios de paisajismo",
        image: "src/assets/nice.png",
        link: "#",
        clas: "md:w-[347px] md:h-[260px]",
        estado: "Coming soon",
        color: "bg-rojo",
        items: [
            { iconClass: "fas fa-rocket", name: "Astro" },
            { iconClass: "fab fa-js", name: "JavaScript" },
            { iconClass: "fas fa-leaf", name: "Jardinería" },
        ],
    },
    {
        title: "E-commerce hg",
        description: "Tienda online con panel de administración",
        image: "src/assets/nice.png",
        link: "#",
        clas: "md:w-[190px] md:h-[260px]",
        estado: "Completado",
        color: "bg-turquesa",
        items: [
            { iconClass: "fab fa-js", name: "JavaScript" },
            { iconClass: "fab fa-node-js", name: "Node.js" },
            { iconClass: "fas fa-shopping-cart", name: "E-commerce" },
        ],
    },
    {
        title: "Juego farm",
        description: "Experiencia interactiva de simulación agrícola",
        image: "src/assets/nice.png",
        link: "#",
        clas: "md:w-[190px] md:h-[260px]",
        estado: "Coming soon",
        color: "bg-rojo",
        items: [
            { iconClass: "fab fa-js", name: "JavaScript" },
            { iconClass: "fas fa-tractor", name: "Phaser" },
            { iconClass: "fas fa-chart-area", name: "Simulación" },
        ],
    },
    {
        title: "Page componentes y animaciones",
        description: "Biblioteca de elementos UI interactivos",
        image: "src/assets/nice.png",
        link: "#",
        clas: "md:w-[190px] md:h-[260px]",
        estado: "Coming soon",
        color: "bg-rojo",
        items: [
            { iconClass: "fas fa-rocket", name: "Astro" },
            { iconClass: "fab fa-js", name: "JavaScript" },
            { iconClass: "fas fa-paint-brush", name: "Animaciones" },
        ],
    },
  ];